### ISSUE TITLE
Update all plugins

### ISSUE THREAD

**Issue by Fuglen** [theflyingbirdsmc/TFB-Network#114]
**As a(n)** Admin
**I want to** keep my plugins updated
**So that** we can get the new features and fixes

**Detailed description:**

- [x] ArmorStandTools
- [ ] BungeeControl-Red
- [x] BuycraftX
- [x] BuycraftX-Bungee
- [ ] ChatControlRed [Paid]
- [x] Chunky
- [x] CommandPanels
- [x] CoreProtect
- [x] DecentHolograms
- [x] Essentials
- [x] EssentialsAntiBuild
- [x] EssentialsChat
- [x] EssentialsGeoIP
- [x] EssentialsProtect
- [x] EssentialsSpawn
- [x] Factions
- [x] FastAsyncWorldEdit
- [x] GadgetsMenu [Paid]
- [x] GSit
- [x] ImageOnMap
- [x] LibsDisguises
- [x] LuckPerms
- [x] LuckPerms-Bungee
- [x] Multiverse-Core
- [x] Parkour
- [x] ParkourTopTen
- [x] PlaceholderAPI
- [x] Plan
- [x] PlotSquared [Paid]
- [x] ProtocolLib
- [x] Reconnect
- [x] SuperVanish
- [x] TAB
- [x] Vault
- [x] ViaBackwards
- [x] ViaVersion
- [x] VoidGen
- [x] Votifier (Also go by NuVotifier)
- [x] VotingPlugin
- [x] Vulcan [Paid]
- [x] VulcanBungee
- [x] WorldBorder
- [x] WorldEdit
- [x] WorldGuard
- [x] WorldGuardExtraFlags
- [ ] Paper
- [ ] Flamecord

**Comment by KatieDeForest** [comment]
I'm working on testing them locally.
Please don't change any checkmarks, thank you =^.^=

**Comment by KatieDeForest** [comment]
I'm unable to do the last 4 tasks.
Hopefully @Fuglen can do something about that ❤️
