### ISSUE TITLE
Re-add TFB player count on Discord

### ISSUE THREAD

**Issue by Fuglen** [theflyingbirdsmc/TFB-Network#131]
**As a(n)** member of TFB's Discord
**I want to** see how many players are online on the network
**So that** I get motivated to join in on the fun

**Detailed description:**
Before we could only see a total number of players that were currently online, but it might be possible to show individual servers because that's what players actually might want to see. 

What we possibly want is to see how many total players are online and also if possible in a dedicated channel where it shows which servers on the network where there are players, names of players are not important here.

I added GameStatus bot to our Discord to check it out but it's not as expected. https://top.gg/bot/961389454201860156
I also found this which is interesting https://www.spigotmc.org/resources/discord-statusbot.91444/

Should we develop our own custom bot to do what we want?

**Comment by lucas2kdk** [comment]
![image](https://user-images.githubusercontent.com/43099632/222545029-e8aababb-7e87-477a-91b6-a30f7ff1e5a2.png)
