### ISSUE TITLE
[BUG] Exclusive update for parkour

### ISSUE THREAD

**Issue by KatieDeForest** [theflyingbirdsmc/TFB-Network#143]
**Describe the bug**
Me and the Devs of the Parkour and ParkourTopTen plugin, have found out that if the server crashes, gets force killed or stops within 20 seconds of server startup. The config files don't load properly, and gets corrupted, causing them to override themselves.
This has caused all our parkour course times to reset multiple times, and we would like to avoid that by updating the plugin with hopefully a fix. 

**To Reproduce**
Crash, force kill or stop the server within 20 seconds to corrupt the config files.

**Expected behavior**
The configs from the ParkourTopTen plugin is supposed to be read every time the server started up, by the Parkour plugin.
But any disturbance avoids this, and therefor the Devs have done so the configs only gets read whenever there's an update, change or deletion in the config files.

**Screenshots**
![image](https://user-images.githubusercontent.com/32366847/226136348-953416a4-fcb0-436f-85b4-a7fa9554657b.png)

**Server (please complete the following information):**
 - Version: 1.19.X
 - Plugins:  Parkour-7.1.0, getting updated to 7.2.0.... ParkourTopTen-4.0, getting updated to 4.1

**Additional context**
This isn't a guarantied fix, but hopefully it works. I've promised to get back to the Devs with an update on whether it fixed the issue or not, once I've tested this on a local server.

**Comment by Fuglen** [comment]
I wonder why you are not able to reproduce this locally, is there any data/courses from Live or?

The whole idea of having a local development environment is for issues exactly like this, so let's see if we together can reproduce it and fix it after the update 😉👍

**Comment by KatieDeForest** [comment]
You misunderstood, I've texted you on discord
