### ISSUE TITLE
Customize chat motd for all servers

### ISSUE THREAD

**Issue by Fuglen** [theflyingbirdsmc/TFB-Network#160]
**As a(n)** player 
**I want to** get greeted by a custom motd
**So that** I can see updates, tips, votes, referrals etc when I log in. 

**Detailed description:**
As staff, I want to promote all the things that matters for players when they log in, so it's more likely they will use vote, refer friends, use tips etc. 
When players join the chat is most likely being used, we want players able to read whole motd without getting disturbed. 

- [x] Make a nice motd for Lobby. 
- [x] Make a motd for returning players in Lobby
- [ ] Create motd template for servers
- [ ] Figure out how to keep chat clear/paused. 

For returning players, we should show them what's related when they come back:
- Voting
- A random tip
- Links
- Players online
- News?

**Comment by Fuglen** [comment]
![image](https://user-images.githubusercontent.com/6181362/235254059-6b0142a1-6484-4e6e-941c-7d3cfeed15ed.png)
![image](https://user-images.githubusercontent.com/6181362/235254062-89e170cc-a7a5-4e87-8eaf-38240528e57c.png)
Just some chat motds from Freakyville xD

**Comment by TheFlyingBirds** [comment]
This is how MOTD for the lobby looks like for new players
![image](https://github.com/theflyingbirdsmc/TFB-Network/assets/7267471/f79f9fa6-d3ee-4f2b-a4cd-3118f3a1265f)

**Comment by Fuglen** [comment]
This MOTD is for returning players
![image](https://github.com/theflyingbirdsmc/TFB-Network/assets/6181362/6918bb78-991f-4d8a-92a6-534ba2f424f8)
