### ISSUE TITLE
TFB website

### ISSUE THREAD

**Issue by Fuglen** [theflyingbirdsmc/TFB-Network#5]
Fuglen should definitely make a nice website for TFB using Umbraco because it's amazing and free for him ;)

It should be modern with links to everything TFB related, maybe even have some blogs/news?
Not to forget pages for "about us", "contact" and "meet the team"!
It should use some data from Plan, so you can see how many players you can join online/total right now.

**Comment by lucas2kdk** [comment]
https://www.theflyingbirds.net/

**Comment by lucas2kdk** [comment]
Closing #5
