### ISSUE TITLE
Setup StreamingDrops for whole network

### ISSUE THREAD

**Issue by Fuglen** [theflyingbirdsmc/TFB-Network#7]
StreamingDrops gives the option to show when specific players are live on Twitch, which should be shown with a red dot (LIVE) to show they are live on Twitch in the TAB list in Minecraft.

Also, the channel name and link could be in the description(hover name in chat) of the streamer and gets a link when clicked on them.

Plugin: https://www.spigotmc.org/resources/streamingdrops-1-8-8-1-18-x-twitch-drops-for-minecraft-server-discord-integration.76996/

**Comment by Fuglen** [comment]
Kinda a bummer that the only plugin out there with these features is not supporting Bungeecord. 
Something to do with that he cannot detect which server the streamer plays on because of Bungee and therefore the streamer have to use "#StreamingDrop" in their stream title on Twitch. 

If Bungee support is out of question, then maybe a custom tag like "#TFB"?

Read more here: https://github.com/morelaid/StreamDrops/wiki/BungeeCord#what-is-the-global-streamer-tag-globalstreamertag

**Comment by lucas2kdk** [comment]
Can we use a Array of tags ?
